/* Dummy wrappers,  */
void coq_push_vstack(void) {}
void coq_push_ra(void) {}
void coq_push_arguments(void) {}
void coq_push_val(void) {}
void coq_pushpop(void) {}
void coq_set_drawinstr(void) {}
void coq_interprete_ml(void) {}
void coq_interprete_byte(void) {}
void coq_offset_closure(void) {}
void coq_closure_arity(void) {}
void coq_is_double(void) {}
void coq_offset(void) {}
void coq_eval_tcode(void) {}
void coq_tcode_of_code(void) {}
void coq_kind_of_closure(void) {}
void coq_int_tcode(void) {}
void coq_makeaccu(void) {}
void init_coq_vm(void) {}
void coq_is_accumulate_code(void) {}
void coq_set_bytecode_field(void) {}
void coq_tcode_array(void) {}
void coq_offset_tcode(void) {}
void accumulate_code(void) {}
void coq_next_up(void) {}
void coq_next_up_byte(void) {}
void coq_next_down(void) {}
void coq_next_down_byte(void) {}
void coq_fsqrt(void) {}
void coq_fsqrt_byte(void) {}
void coq_fadd(void) {}
void coq_fadd_byte(void) {}
void coq_fsub(void) {}
void coq_fsub_byte(void) {}
void coq_fdiv(void) {}
void coq_fdiv_byte(void) {}
void coq_fmul(void) {}
void coq_fmul_byte(void) {}
void coq_uint63_to_float(void) {}
void coq_uint63_to_float_byte(void) {}
