(* File automatically generated by the configure script *)
let libdir = "/nonexistent"
let pluginsdir = "/nonexistent"
let preludesdir = "/nonexistent"
let datadir = "/nonexistent"
let mandir = "/nonexistent"
